
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.112.124.237/bunnyroom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yyc
    password: yyc
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop